### PR TITLE
Entity reference fields break on entity types with only one bundle

### PR DESCRIPTION
**Pull request by BramDriesen**
Currently when you have an entity reference field that uses a entity type that can only have one bundle (for example the contrib module's "poll" entity) the `getMatches` query breaks. Because it tries to make a field query on an empty field.

The query Site studio builds:
image

The query a regular entity reference field on POLL makes:
image

Simply resetting the $bundles array to a single item when there is only one bundle (or even setting it to NULL) solves this issue.

This fix can be done in either the `\Drupal\cohesion\Controller\CohesionDrupalEndpointController::runAutoComplete` for which I made the pull request. Or in `\Drupal\cohesion\Entity\CohesionEntityAutocompleteMatcher::getMatches` where the `$selection_settings` contains the value from the controller.

I will also log a ticket through Acquia Support for this.

### CODE REVIEW

**Comment by BramDriesen** [comment]
This also throws following error: 

`Drupal\Core\Entity\Query\QueryException: '' not found in Drupal\Core\Entity\Query\Sql\Tables->ensureEntityTable() (line 369 of /var/www/html/docroot/core/lib/Drupal/Core/Entity/Query/Sql/Tables.php).`

**Comment by BramDriesen** [comment]
Case number: 00928848

**Comment by BramDriesen** [comment]
Before fix:
Screenshot 2023-03-01 at 19 56 51
After fix:
Screenshot 2023-03-01 at 19 57 16

**Comment by BramDriesen** [comment]
This is also impacting core entities like Users

**Comment by BramDriesen** [comment]
@cohesion-flotz Maybe comment why you close it? I still see no fix in 7.0.x

**Comment by cohesion-flotz** [comment]
Sorry about this @BramDriesen - everything is automated using my user account on this repo.
I have reached to the Site Studio team about your PR and they will see what they can do about it 👍

**Comment by sgrichards** [comment]
@BramDriesen - appreciate your contribution here. We have these changes in our development respository now under review and will release to 7.0.x asap.

**Comment by BramDriesen** [comment]
Thanks @sgrichards & @cohesion-flotz much appreciated 😄

**Pull request closed without merging**
